services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    command: --noauth
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=$ME_CONFIG_MONGODB_SERVER
    env_file:
      - ./.env
