name: Complete Workflow

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        mongodb-version: [4.2]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - name: Install devDependencies
        run: yarn --frozen-lockfile
      - name: Run all tests
        run: yarn test

      - shell: bash
        if: github.ref == 'refs/heads/master'
        name: Create SSH deployment key
        env:
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: ./scripts/deploy.sh

      - name: Deployment
        if: github.ref == 'refs/heads/master'
        run: git remote add umbler ssh://git@kamino.deploy.umbler.com:9922/k46wov8j/surf-forecast-api-com.git && git push umbler master
        env:
          CI: true
